---@type LiquidKeyboard
local liquid = liquid {
  columns = 6,
  row = 5,
  bottom_padding = 20,
  keyboards = {
    { id = "history", type = "HISTORY", name = "常用" },
    { id = "ascii", type = "SINGLE", name = "英文",
      keys = {
        -- 常用标点
        { text = "," }, { text = "." }, { text = "!" }, { text = "?" },
        { text = ";" }, { text = ":" }, { text = "'" }, { text = '"' },
        -- 括号
        { text = "(" }, { text = ")" }, { text = "[" }, { text = "]" },
        { text = "{" }, { text = "}" }, { text = "<" }, { text = ">" },
        -- 数学
        { text = "+" }, { text = "-" }, { text = "*" }, { text = "/" },
        { text = "=" }, { text = "%" }, { text = "^" }, { text = "~" },
        -- 特殊
        { text = "@" }, { text = "#" }, { text = "$" }, { text = "&" },
        { text = "_" }, { text = "\\" }, { text = "|" }, { text = "`" }
      } },
    { id = "cn", type = "SINGLE", name = "中文",
      keys = {
        -- 1. 高频标点 (48)
        { text = "！" }, { text = "＂" }, { text = "＃" }, { text = "＄" },
        { text = "％" }, { text = "＆" }, { text = "＇" }, { text = "（" },
        { text = "）" }, { text = "＊" }, { text = "＋" }, { text = "，" },
        { text = "－" }, { text = "．" }, { text = "／" }, { text = "：" },
        { text = "；" }, { text = "＜" }, { text = "＝" }, { text = "＞" },
        { text = "？" }, { text = "＠" }, { text = "［" }, { text = "］" },
        { text = "｛" }, { text = "｜" }, { text = "｝" }, { text = "～" },
        { text = "０" }, { text = "１" }, { text = "２" }, { text = "３" },
        { text = "４" }, { text = "５" }, { text = "６" }, { text = "７" },
        { text = "８" }, { text = "９" }, { text = "￥" }, { text = "、" },
        { text = "。" }, { text = "〃" }, { text = "々" }, { text = "〇" },
        { text = "＼" }, { text = "＾" }, { text = "＿" }, { text = "｀" },
        -- 2. 括号/引号 (25)
        { text = "〈" }, { text = "〉" }, { text = "《" }, { text = "》" },
        { text = "「" }, { text = "」" }, { text = "『" }, { text = "』" },
        { text = "【" }, { text = "】" }, { text = "〔" }, { text = "〕" },
        { text = "〖" }, { text = "〗" }, { text = "〘" }, { text = "〙" },
        { text = "〚" }, { text = "〛" }, { text = "〝" }, { text = "〞" },
        { text = "〟" }, { text = "｟" }, { text = "｠" }, { text = "｢" },
        { text = "｣" },
        -- 3. 竖排兼容括号 (23)
        { text = "︵" }, { text = "︶" }, { text = "︷" }, { text = "︸" },
        { text = "︹" }, { text = "︺" }, { text = "︻" }, { text = "︼" },
        { text = "︽" }, { text = "︾" }, { text = "︿" }, { text = "﹀" },
        { text = "﹁" }, { text = "﹂" }, { text = "﹃" }, { text = "﹄" },
        { text = "﹇" }, { text = "﹈" }, { text = "︰" }, { text = "︱" },
        { text = "︲" }, { text = "︳" }, { text = "︴" },
        -- 4. 小型变体标点 (28)
        { text = "﹐" }, { text = "﹑" }, { text = "﹒" }, { text = "﹔" },
        { text = "﹕" }, { text = "﹖" }, { text = "﹗" }, { text = "﹘" },
        { text = "﹙" }, { text = "﹚" }, { text = "﹛" }, { text = "﹜" },
        { text = "﹝" }, { text = "﹞" }, { text = "﹟" }, { text = "﹠" },
        { text = "﹡" }, { text = "﹢" }, { text = "﹣" }, { text = "﹤" },
        { text = "﹥" }, { text = "﹦" }, { text = "﹨" }, { text = "﹩" },
        { text = "﹪" }, { text = "﹫" }, { text = "﹅" }, { text = "﹆" },
        -- 5. 装饰线/标记 (14)
        { text = "〜" }, { text = "〰" }, { text = "﹉" }, { text = "﹊" },
        { text = "﹋" }, { text = "﹌" }, { text = "﹍" }, { text = "﹎" },
        { text = "﹏" }, { text = "〄" }, { text = "〒" }, { text = "〓" },
        { text = "〆" }, { text = "〠" },
        -- 6. 专用/历史符号 (46)
        { text = "〡" }, { text = "〢" }, { text = "〣" }, { text = "〤" },
        { text = "〥" }, { text = "〦" }, { text = "〧" }, { text = "〨" },
        { text = "〩" }, { text = "〸" }, { text = "〹" }, { text = "〺" },
        { text = "〪" }, { text = "〫" }, { text = "〬" }, { text = "〭" },
        { text = "〮" }, { text = "〯" }, { text = "〱" }, { text = "〲" },
        { text = "〳" }, { text = "〴" }, { text = "〵" }, { text = "〶" },
        { text = "〷" }, { text = "〻" }, { text = "〼" }, { text = "〽" },
        { text = "〾" }, { text = "〿" }, { text = "　" }, { text = "￠" },
        { text = "￡" }, { text = "￢" }, { text = "￣" }, { text = "￤" },
        { text = "￦" }, { text = "￨" }, { text = "￩" }, { text = "￪" },
        { text = "￫" }, { text = "￬" }, { text = "￭" }, { text = "￮" },
        { text = "｡" }, { text = "､" }
      } },
    { id = "stroke", type = "SINGLE", name = "笔画",
      keys = {
        { text = "㇀" }, { text = "㇁" }, { text = "㇂" }, { text = "㇃" },
        { text = "㇄" }, { text = "㇅" }, { text = "㇆" }, { text = "㇇" },
        { text = "㇈" }, { text = "㇉" }, { text = "㇊" }, { text = "㇋" },
        { text = "㇌" }, { text = "㇍" }, { text = "㇎" }, { text = "㇏" },
        { text = "㇐" }, { text = "㇑" }, { text = "㇒" }, { text = "㇓" },
        { text = "㇔" }, { text = "㇕" }, { text = "㇖" }, { text = "㇗" },
        { text = "㇘" }, { text = "㇙" }, { text = "㇚" }, { text = "㇛" },
        { text = "㇜" }, { text = "㇝" }, { text = "㇞" }, { text = "㇟" },
        { text = "㇠" }, { text = "㇡" }, { text = "㇢" }, { text = "㇣" },
        { text = "㇤" }, { text = "㇥" }, { text = "㇯" }
      } },
    { id = "math", type = "SINGLE", name = "数学",
      keys = {
        -- 基本运算
        { text = "+" }, { text = "-" }, { text = "×" }, { text = "÷" },
        { text = "=" }, { text = "±" }, { text = "≠" }, { text = "≈" },
        -- 比较
        { text = "<" }, { text = ">" }, { text = "≤" }, { text = "≥" },
        { text = "≦" }, { text = "≧" }, { text = "≮" }, { text = "≯" },
        -- 逻辑与集合
        { text = "∧" }, { text = "∨" }, { text = "∩" }, { text = "∪" },
        { text = "∈" }, { text = "∝" }, { text = "∀" }, { text = "∃" },
        -- 求和/积分/根号
        { text = "∑" }, { text = "∏" }, { text = "∫" }, { text = "∮" },
        { text = "√" }, { text = "∛" }, { text = "∟" }, { text = "∞" },
        -- 其他运算
        { text = "∠" }, { text = "∥" }, { text = "≡" }, { text = "≒" },
        { text = "⊕" }, { text = "⊙" }, { text = "∽" }, { text = "∴" },
        -- 函数/符号
        { text = "∵" }, { text = "∷" }, { text = "⊥" }, { text = "⊿" },
        { text = "∂" }, { text = "∇" }, { text = "∝" }, { text = "‰" },
        -- 希腊小写
        { text = "α" }, { text = "β" }, { text = "γ" }, { text = "δ" },
        { text = "θ" }, { text = "λ" }, { text = "π" }, { text = "σ" },
        -- 希腊大写/其他
        { text = "Δ" }, { text = "Ω" }, { text = "Π" }, { text = "Σ" },
        { text = "Φ" }, { text = "ω" }, { text = "μ" }, { text = "φ" }
      } },
    { id = "ids", type = "SINGLE", name = "结构",
      keys = {
        -- U+2FF0 IDS 结构描述符 (12)
        { text = "⿰" }, { text = "⿱" }, { text = "⿲" }, { text = "⿳" },
        { text = "⿴" }, { text = "⿵" }, { text = "⿶" }, { text = "⿷" },
        { text = "⿸" }, { text = "⿹" }, { text = "⿺" }, { text = "⿻" }
      } },
    { id = "number", type = "SINGLE", name = "序号",
      keys = {
        -- 圈号 ①-⑯
        { text = "①" }, { text = "②" }, { text = "③" }, { text = "④" },
        { text = "⑤" }, { text = "⑥" }, { text = "⑦" }, { text = "⑧" },
        { text = "⑨" }, { text = "⑩" }, { text = "⑪" }, { text = "⑫" },
        { text = "⑬" }, { text = "⑭" }, { text = "⑮" }, { text = "⑯" },
        -- 弧括号 ⑴-⒃
        { text = "⑴" }, { text = "⑵" }, { text = "⑶" }, { text = "⑷" },
        { text = "⑸" }, { text = "⑹" }, { text = "⑺" }, { text = "⑻" },
        { text = "⑼" }, { text = "⑽" }, { text = "⑾" }, { text = "⑿" },
        { text = "⒀" }, { text = "⒁" }, { text = "⒂" }, { text = "⒃" },
        -- 点号 ⒈-⒗
        { text = "⒈" }, { text = "⒉" }, { text = "⒊" }, { text = "⒋" },
        { text = "⒌" }, { text = "⒍" }, { text = "⒎" }, { text = "⒏" },
        { text = "⒐" }, { text = "⒑" }, { text = "⒒" }, { text = "⒓" },
        { text = "⒔" }, { text = "⒕" }, { text = "⒖" }, { text = "⒗" },
        -- 黑圈号 ❶-⓰(16)
        { text = "❶" }, { text = "❷" }, { text = "❸" }, { text = "❹" },
        { text = "❺" }, { text = "❻" }, { text = "❼" }, { text = "❽" },
        { text = "❾" }, { text = "❿" }, { text = "⓫" }, { text = "⓬" },
        { text = "⓭" }, { text = "⓮" }, { text = "⓯" }, { text = "⓰" },
        -- 中文圈号 ㈠-㈧
        { text = "㈠" }, { text = "㈡" }, { text = "㈢" }, { text = "㈣" },
        { text = "㈤" }, { text = "㈥" }, { text = "㈦" }, { text = "㈧" },
        { text = "㊀" }, { text = "㊁" }, { text = "㊂" }, { text = "㊃" },
        { text = "㊄" }, { text = "㊅" }, { text = "㊆" }, { text = "㊇" },
        -- 罗马数字 Ⅰ-Ⅻ, ⅰ-ⅻ
        { text = "Ⅰ" }, { text = "Ⅱ" }, { text = "Ⅲ" }, { text = "Ⅳ" },
        { text = "Ⅴ" }, { text = "Ⅵ" }, { text = "Ⅶ" }, { text = "Ⅷ" },
        { text = "Ⅸ" }, { text = "Ⅹ" }, { text = "Ⅺ" }, { text = "Ⅻ" },
        { text = "ⅰ" }, { text = "ⅱ" }, { text = "ⅲ" }, { text = "ⅳ" }
      } },
    { id = "emoji_smileys", type = "SINGLE", name = "表情",
      keys = {
        { text = "😀" }, { text = "😃" }, { text = "😄" }, { text = "😁" },
        { text = "😆" }, { text = "😅" }, { text = "🤣" }, { text = "😂" },
        { text = "🙂" }, { text = "🙃" }, { text = "🫠" }, { text = "😉" },
        { text = "😊" }, { text = "😇" }, { text = "🥰" }, { text = "😍" },
        { text = "🤩" }, { text = "😘" }, { text = "😗" }, { text = "☺️" },
        { text = "😚" }, { text = "😙" }, { text = "🥲" }, { text = "😋" },
        { text = "😛" }, { text = "😜" }, { text = "🤪" }, { text = "😝" },
        { text = "🤑" }, { text = "🤗" }, { text = "🤭" }, { text = "🫢" },
        { text = "🫣" }, { text = "🤫" }, { text = "🤔" }, { text = "🫡" },
        { text = "🤐" }, { text = "🤨" }, { text = "😐" }, { text = "😑" },
        { text = "😶" }, { text = "🫥" }, { text = "😶‍🌫️" }, { text = "😏" },
        { text = "😒" }, { text = "🙄" }, { text = "😬" }, { text = "😮‍💨" },
        { text = "🤥" }, { text = "🫨" }, { text = "🙂‍↔️" }, { text = "🙂‍↕️" },
        { text = "😌" }, { text = "😔" }, { text = "😪" }, { text = "🤤" },
        { text = "😴" }, { text = "🫩" }, { text = "😷" }, { text = "🤒" },
        { text = "🤕" }, { text = "🤢" }, { text = "🤮" }, { text = "🤧" },
        { text = "🥵" }, { text = "🥶" }, { text = "🥴" }, { text = "😵" },
        { text = "😵‍💫" }, { text = "🤯" }, { text = "🤠" }, { text = "🥳" },
        { text = "🥸" }, { text = "😎" }, { text = "🤓" }, { text = "🧐" },
        { text = "😕" }, { text = "🫤" }, { text = "😟" }, { text = "🙁" },
        { text = "☹️" }, { text = "😮" }, { text = "😯" }, { text = "😲" },
        { text = "😳" }, { text = "🫪" }, { text = "🥺" }, { text = "🥹" },
        { text = "😦" }, { text = "😧" }, { text = "😨" }, { text = "😰" },
        { text = "😥" }, { text = "😢" }, { text = "😭" }, { text = "😱" },
        { text = "😖" }, { text = "😣" }, { text = "😞" }, { text = "😓" },
        { text = "😩" }, { text = "😫" }, { text = "🥱" }, { text = "😤" },
        { text = "😡" }, { text = "😠" }, { text = "🤬" }, { text = "😈" },
        { text = "👿" }, { text = "💀" }, { text = "☠️" }, { text = "💩" },
        { text = "🤡" }, { text = "👹" }, { text = "👺" }, { text = "👻" },
        { text = "👽" }, { text = "👾" }, { text = "🤖" }, { text = "😺" },
        { text = "😸" }, { text = "😹" }, { text = "😻" }, { text = "😼" },
        { text = "😽" }, { text = "🙀" }, { text = "😿" }, { text = "😾" },
        { text = "🙈" }, { text = "🙉" }, { text = "🙊" }, { text = "💌" },
        { text = "💘" }, { text = "💝" }, { text = "💖" }, { text = "💗" },
        { text = "💓" }, { text = "💞" }, { text = "💕" }, { text = "💟" },
        { text = "❣️" }, { text = "💔" }, { text = "❤️‍🔥" }, { text = "❤️‍🩹" },
        { text = "❤️" }, { text = "🩷" }, { text = "🧡" }, { text = "💛" },
        { text = "💚" }, { text = "💙" }, { text = "🩵" }, { text = "💜" },
        { text = "🤎" }, { text = "🖤" }, { text = "🩶" }, { text = "🤍" },
        { text = "💋" }, { text = "💯" }, { text = "💢" }, { text = "🫯" },
        { text = "💥" }, { text = "💫" }, { text = "💦" }, { text = "💨" },
        { text = "🕳️" }, { text = "💬" }, { text = "👁️‍🗨️" }, { text = "🗨️" },
        { text = "🗯️" }, { text = "💭" }, { text = "💤" }
      } },
    { id = "emoji_gestures", type = "SINGLE", name = "手势",
      keys = {
        { text = "👋" }, { text = "🤚" }, { text = "🖐️" }, { text = "✋" },
        { text = "🖖" }, { text = "🫱" }, { text = "🫲" }, { text = "🫳" },
        { text = "🫴" }, { text = "🫷" }, { text = "🫸" }, { text = "👌" },
        { text = "🤌" }, { text = "🤏" }, { text = "✌️" }, { text = "🤞" },
        { text = "🫰" }, { text = "🤟" }, { text = "🤘" }, { text = "🤙" },
        { text = "👈" }, { text = "👉" }, { text = "👆" }, { text = "🖕" },
        { text = "👇" }, { text = "☝️" }, { text = "🫵" }, { text = "👍" },
        { text = "👎" }, { text = "✊" }, { text = "👊" }, { text = "🤛" },
        { text = "🤜" }, { text = "👏" }, { text = "🙌" }, { text = "🫶" },
        { text = "👐" }, { text = "🤲" }, { text = "🤝" }, { text = "🙏" },
        { text = "✍️" }, { text = "💅" }, { text = "🤳" }
      } },
    { id = "emoji_people", type = "SINGLE", name = "人物",
      keys = {
        { text = "💪" }, { text = "🦾" }, { text = "🦿" }, { text = "🦵" },
        { text = "🦶" }, { text = "👂" }, { text = "🦻" }, { text = "👃" },
        { text = "🧠" }, { text = "🫀" }, { text = "🫁" }, { text = "🦷" },
        { text = "🦴" }, { text = "👀" }, { text = "👁️" }, { text = "👅" },
        { text = "👄" }, { text = "🫦" }, { text = "👶" }, { text = "🧒" },
        { text = "👦" }, { text = "👧" }, { text = "🧑" }, { text = "👱" },
        { text = "👨" }, { text = "🧔" }, { text = "🧔‍♂️" }, { text = "🧔‍♀️" },
        { text = "👨‍🦰" }, { text = "👨‍🦱" }, { text = "👨‍🦳" }, { text = "👨‍🦲" },
        { text = "👩" }, { text = "👩‍🦰" }, { text = "🧑‍🦰" }, { text = "👩‍🦱" },
        { text = "🧑‍🦱" }, { text = "👩‍🦳" }, { text = "🧑‍🦳" }, { text = "👩‍🦲" },
        { text = "🧑‍🦲" }, { text = "👱‍♀️" }, { text = "👱‍♂️" }, { text = "🧓" },
        { text = "👴" }, { text = "👵" }, { text = "🙍" }, { text = "🙍‍♂️" },
        { text = "🙍‍♀️" }, { text = "🙎" }, { text = "🙎‍♂️" }, { text = "🙎‍♀️" },
        { text = "🙅" }, { text = "🙅‍♂️" }, { text = "🙅‍♀️" }, { text = "🙆" },
        { text = "🙆‍♂️" }, { text = "🙆‍♀️" }, { text = "💁" }, { text = "💁‍♂️" },
        { text = "💁‍♀️" }, { text = "🙋" }, { text = "🙋‍♂️" }, { text = "🙋‍♀️" },
        { text = "🧏" }, { text = "🧏‍♂️" }, { text = "🧏‍♀️" }, { text = "🙇" },
        { text = "🙇‍♂️" }, { text = "🙇‍♀️" }, { text = "🤦" }, { text = "🤦‍♂️" },
        { text = "🤦‍♀️" }, { text = "🤷" }, { text = "🤷‍♂️" }, { text = "🤷‍♀️" },
        { text = "🧑‍⚕️" }, { text = "👨‍⚕️" }, { text = "👩‍⚕️" }, { text = "🧑‍🎓" },
        { text = "👨‍🎓" }, { text = "👩‍🎓" }, { text = "🧑‍🏫" }, { text = "👨‍🏫" },
        { text = "👩‍🏫" }, { text = "🧑‍⚖️" }, { text = "👨‍⚖️" }, { text = "👩‍⚖️" },
        { text = "🧑‍🌾" }, { text = "👨‍🌾" }, { text = "👩‍🌾" }, { text = "🧑‍🍳" },
        { text = "👨‍🍳" }, { text = "👩‍🍳" }, { text = "🧑‍🔧" }, { text = "👨‍🔧" },
        { text = "👩‍🔧" }, { text = "🧑‍🏭" }, { text = "👨‍🏭" }, { text = "👩‍🏭" },
        { text = "🧑‍💼" }, { text = "👨‍💼" }, { text = "👩‍💼" }, { text = "🧑‍🔬" },
        { text = "👨‍🔬" }, { text = "👩‍🔬" }, { text = "🧑‍💻" }, { text = "👨‍💻" },
        { text = "👩‍💻" }, { text = "🧑‍🎤" }, { text = "👨‍🎤" }, { text = "👩‍🎤" },
        { text = "🧑‍🎨" }, { text = "👨‍🎨" }, { text = "👩‍🎨" }, { text = "🧑‍✈️" },
        { text = "👨‍✈️" }, { text = "👩‍✈️" }, { text = "🧑‍🚀" }, { text = "👨‍🚀" },
        { text = "👩‍🚀" }, { text = "🧑‍🚒" }, { text = "👨‍🚒" }, { text = "👩‍🚒" },
        { text = "👮" }, { text = "👮‍♂️" }, { text = "👮‍♀️" }, { text = "🕵️" },
        { text = "🕵️‍♂️" }, { text = "🕵️‍♀️" }, { text = "💂" }, { text = "💂‍♂️" },
        { text = "💂‍♀️" }, { text = "🥷" }, { text = "👷" }, { text = "👷‍♂️" },
        { text = "👷‍♀️" }, { text = "🫅" }, { text = "🤴" }, { text = "👸" },
        { text = "👳" }, { text = "👳‍♂️" }, { text = "👳‍♀️" }, { text = "👲" },
        { text = "🧕" }, { text = "🤵" }, { text = "🤵‍♂️" }, { text = "🤵‍♀️" },
        { text = "👰" }, { text = "👰‍♂️" }, { text = "👰‍♀️" }, { text = "🤰" },
        { text = "🫃" }, { text = "🫄" }, { text = "🤱" }, { text = "👩‍🍼" },
        { text = "👨‍🍼" }, { text = "🧑‍🍼" }, { text = "👼" }, { text = "🎅" },
        { text = "🤶" }, { text = "🧑‍🎄" }, { text = "🦸" }, { text = "🦸‍♂️" },
        { text = "🦸‍♀️" }, { text = "🦹" }, { text = "🦹‍♂️" }, { text = "🦹‍♀️" },
        { text = "🧙" }, { text = "🧙‍♂️" }, { text = "🧙‍♀️" }, { text = "🧚" },
        { text = "🧚‍♂️" }, { text = "🧚‍♀️" }, { text = "🧛" }, { text = "🧛‍♂️" },
        { text = "🧛‍♀️" }, { text = "🧜" }, { text = "🧜‍♂️" }, { text = "🧜‍♀️" },
        { text = "🧝" }, { text = "🧝‍♂️" }, { text = "🧝‍♀️" }, { text = "🧞" },
        { text = "🧞‍♂️" }, { text = "🧞‍♀️" }, { text = "🧟" }, { text = "🧟‍♂️" },
        { text = "🧟‍♀️" }, { text = "🧌" }, { text = "🫈" }, { text = "💆" },
        { text = "💆‍♂️" }, { text = "💆‍♀️" }, { text = "💇" }, { text = "💇‍♂️" },
        { text = "💇‍♀️" }, { text = "🚶" }, { text = "🚶‍♂️" }, { text = "🚶‍♀️" },
        { text = "🚶‍➡️" }, { text = "🚶‍♀️‍➡️" }, { text = "🚶‍♂️‍➡️" }, { text = "🧍" },
        { text = "🧍‍♂️" }, { text = "🧍‍♀️" }, { text = "🧎" }, { text = "🧎‍♂️" },
        { text = "🧎‍♀️" }, { text = "🧎‍➡️" }, { text = "🧎‍♀️‍➡️" }, { text = "🧎‍♂️‍➡️" },
        { text = "🧑‍🦯" }, { text = "🧑‍🦯‍➡️" }, { text = "👨‍🦯" }, { text = "👨‍🦯‍➡️" },
        { text = "👩‍🦯" }, { text = "👩‍🦯‍➡️" }, { text = "🧑‍🦼" }, { text = "🧑‍🦼‍➡️" },
        { text = "👨‍🦼" }, { text = "👨‍🦼‍➡️" }, { text = "👩‍🦼" }, { text = "👩‍🦼‍➡️" },
        { text = "🧑‍🦽" }, { text = "🧑‍🦽‍➡️" }, { text = "👨‍🦽" }, { text = "👨‍🦽‍➡️" },
        { text = "👩‍🦽" }, { text = "👩‍🦽‍➡️" }, { text = "🏃" }, { text = "🏃‍♂️" },
        { text = "🏃‍♀️" }, { text = "🏃‍➡️" }, { text = "🏃‍♀️‍➡️" }, { text = "🏃‍♂️‍➡️" },
        { text = "🧑‍🩰" }, { text = "💃" }, { text = "🕺" }, { text = "🕴️" },
        { text = "👯" }, { text = "👯‍♂️" }, { text = "👯‍♀️" }, { text = "🧖" },
        { text = "🧖‍♂️" }, { text = "🧖‍♀️" }, { text = "🧗" }, { text = "🧗‍♂️" },
        { text = "🧗‍♀️" }, { text = "🤺" }, { text = "🏇" }, { text = "⛷️" },
        { text = "🏂" }, { text = "🏌️" }, { text = "🏌️‍♂️" }, { text = "🏌️‍♀️" },
        { text = "🏄" }, { text = "🏄‍♂️" }, { text = "🏄‍♀️" }, { text = "🚣" },
        { text = "🚣‍♂️" }, { text = "🚣‍♀️" }, { text = "🏊" }, { text = "🏊‍♂️" },
        { text = "🏊‍♀️" }, { text = "⛹️" }, { text = "⛹️‍♂️" }, { text = "⛹️‍♀️" },
        { text = "🏋️" }, { text = "🏋️‍♂️" }, { text = "🏋️‍♀️" }, { text = "🚴" },
        { text = "🚴‍♂️" }, { text = "🚴‍♀️" }, { text = "🚵" }, { text = "🚵‍♂️" },
        { text = "🚵‍♀️" }, { text = "🤸" }, { text = "🤸‍♂️" }, { text = "🤸‍♀️" },
        { text = "🤼" }, { text = "🤼‍♂️" }, { text = "🤼‍♀️" }, { text = "🤽" },
        { text = "🤽‍♂️" }, { text = "🤽‍♀️" }, { text = "🤾" }, { text = "🤾‍♂️" },
        { text = "🤾‍♀️" }, { text = "🤹" }, { text = "🤹‍♂️" }, { text = "🤹‍♀️" },
        { text = "🧘" }, { text = "🧘‍♂️" }, { text = "🧘‍♀️" }, { text = "🛀" },
        { text = "🛌" }, { text = "🧑‍🤝‍🧑" }, { text = "👭" }, { text = "👫" },
        { text = "👬" }, { text = "💏" }, { text = "👩‍❤️‍💋‍👨" }, { text = "👨‍❤️‍💋‍👨" },
        { text = "👩‍❤️‍💋‍👩" }, { text = "💑" }, { text = "👩‍❤️‍👨" }, { text = "👨‍❤️‍👨" },
        { text = "👩‍❤️‍👩" }, { text = "👨‍👩‍👦" }, { text = "👨‍👩‍👧" }, { text = "👨‍👩‍👧‍👦" },
        { text = "👨‍👩‍👦‍👦" }, { text = "👨‍👩‍👧‍👧" }, { text = "👨‍👨‍👦" }, { text = "👨‍👨‍👧" },
        { text = "👨‍👨‍👧‍👦" }, { text = "👨‍👨‍👦‍👦" }, { text = "👨‍👨‍👧‍👧" }, { text = "👩‍👩‍👦" },
        { text = "👩‍👩‍👧" }, { text = "👩‍👩‍👧‍👦" }, { text = "👩‍👩‍👦‍👦" }, { text = "👩‍👩‍👧‍👧" },
        { text = "👨‍👦" }, { text = "👨‍👦‍👦" }, { text = "👨‍👧" }, { text = "👨‍👧‍👦" },
        { text = "👨‍👧‍👧" }, { text = "👩‍👦" }, { text = "👩‍👦‍👦" }, { text = "👩‍👧" },
        { text = "👩‍👧‍👦" }, { text = "👩‍👧‍👧" }, { text = "🗣️" }, { text = "👤" },
        { text = "👥" }, { text = "🫂" }, { text = "👪" }, { text = "🧑‍🧑‍🧒" },
        { text = "🧑‍🧑‍🧒‍🧒" }, { text = "🧑‍🧒" }, { text = "🧑‍🧒‍🧒" }, { text = "👣" },
        { text = "🫆" }
      } },
    { id = "emoji_animals", type = "SINGLE", name = "动物",
      keys = {
        { text = "🐵" }, { text = "🐒" }, { text = "🦍" }, { text = "🦧" },
        { text = "🐶" }, { text = "🐕" }, { text = "🦮" }, { text = "🐕‍🦺" },
        { text = "🐩" }, { text = "🐺" }, { text = "🦊" }, { text = "🦝" },
        { text = "🐱" }, { text = "🐈" }, { text = "🐈‍⬛" }, { text = "🦁" },
        { text = "🐯" }, { text = "🐅" }, { text = "🐆" }, { text = "🐴" },
        { text = "🫎" }, { text = "🫏" }, { text = "🐎" }, { text = "🦄" },
        { text = "🦓" }, { text = "🦌" }, { text = "🦬" }, { text = "🐮" },
        { text = "🐂" }, { text = "🐃" }, { text = "🐄" }, { text = "🐷" },
        { text = "🐖" }, { text = "🐗" }, { text = "🐽" }, { text = "🐏" },
        { text = "🐑" }, { text = "🐐" }, { text = "🐪" }, { text = "🐫" },
        { text = "🦙" }, { text = "🦒" }, { text = "🐘" }, { text = "🦣" },
        { text = "🦏" }, { text = "🦛" }, { text = "🐭" }, { text = "🐁" },
        { text = "🐀" }, { text = "🐹" }, { text = "🐰" }, { text = "🐇" },
        { text = "🐿️" }, { text = "🦫" }, { text = "🦔" }, { text = "🦇" },
        { text = "🐻" }, { text = "🐻‍❄️" }, { text = "🐨" }, { text = "🐼" },
        { text = "🦥" }, { text = "🦦" }, { text = "🦨" }, { text = "🦘" },
        { text = "🦡" }, { text = "🐾" }, { text = "🦃" }, { text = "🐔" },
        { text = "🐓" }, { text = "🐣" }, { text = "🐤" }, { text = "🐥" },
        { text = "🐦" }, { text = "🐧" }, { text = "🕊️" }, { text = "🦅" },
        { text = "🦆" }, { text = "🦢" }, { text = "🦉" }, { text = "🦤" },
        { text = "🪶" }, { text = "🦩" }, { text = "🦚" }, { text = "🦜" },
        { text = "🪽" }, { text = "🐦‍⬛" }, { text = "🪿" }, { text = "🐦‍🔥" },
        { text = "🐸" }, { text = "🐊" }, { text = "🐢" }, { text = "🦎" },
        { text = "🐍" }, { text = "🐲" }, { text = "🐉" }, { text = "🦕" },
        { text = "🦖" }, { text = "🐳" }, { text = "🐋" }, { text = "🐬" },
        { text = "🫍" }, { text = "🦭" }, { text = "🐟" }, { text = "🐠" },
        { text = "🐡" }, { text = "🦈" }, { text = "🐙" }, { text = "🐚" },
        { text = "🪸" }, { text = "🪼" }, { text = "🦀" }, { text = "🦞" },
        { text = "🦐" }, { text = "🦑" }, { text = "🦪" }, { text = "🐌" },
        { text = "🦋" }, { text = "🐛" }, { text = "🐜" }, { text = "🐝" },
        { text = "🪲" }, { text = "🐞" }, { text = "🦗" }, { text = "🪳" },
        { text = "🕷️" }, { text = "🕸️" }, { text = "🦂" }, { text = "🦟" },
        { text = "🪰" }, { text = "🪱" }, { text = "🦠" }, { text = "💐" },
        { text = "🌸" }, { text = "💮" }, { text = "🪷" }, { text = "🏵️" },
        { text = "🌹" }, { text = "🥀" }, { text = "🌺" }, { text = "🌻" },
        { text = "🌼" }, { text = "🌷" }, { text = "🪻" }, { text = "🌱" },
        { text = "🪴" }, { text = "🌲" }, { text = "🌳" }, { text = "🌴" },
        { text = "🌵" }, { text = "🌾" }, { text = "🌿" }, { text = "☘️" },
        { text = "🍀" }, { text = "🍁" }, { text = "🍂" }, { text = "🍃" },
        { text = "🪹" }, { text = "🪺" }, { text = "🍄" }, { text = "🪾" }
      } },
    { id = "emoji_food", type = "SINGLE", name = "食物",
      keys = {
        { text = "🍇" }, { text = "🍈" }, { text = "🍉" }, { text = "🍊" },
        { text = "🍋" }, { text = "🍋‍🟩" }, { text = "🍌" }, { text = "🍍" },
        { text = "🥭" }, { text = "🍎" }, { text = "🍏" }, { text = "🍐" },
        { text = "🍑" }, { text = "🍒" }, { text = "🍓" }, { text = "🫐" },
        { text = "🥝" }, { text = "🍅" }, { text = "🫒" }, { text = "🥥" },
        { text = "🥑" }, { text = "🍆" }, { text = "🥔" }, { text = "🥕" },
        { text = "🌽" }, { text = "🌶️" }, { text = "🫑" }, { text = "🥒" },
        { text = "🥬" }, { text = "🥦" }, { text = "🧄" }, { text = "🧅" },
        { text = "🥜" }, { text = "🫘" }, { text = "🌰" }, { text = "🫚" },
        { text = "🫛" }, { text = "🍄‍🟫" }, { text = "🫜" }, { text = "🍞" },
        { text = "🥐" }, { text = "🥖" }, { text = "🫓" }, { text = "🥨" },
        { text = "🥯" }, { text = "🥞" }, { text = "🧇" }, { text = "🧀" },
        { text = "🍖" }, { text = "🍗" }, { text = "🥩" }, { text = "🥓" },
        { text = "🍔" }, { text = "🍟" }, { text = "🍕" }, { text = "🌭" },
        { text = "🥪" }, { text = "🌮" }, { text = "🌯" }, { text = "🫔" },
        { text = "🥙" }, { text = "🧆" }, { text = "🥚" }, { text = "🍳" },
        { text = "🥘" }, { text = "🍲" }, { text = "🫕" }, { text = "🥣" },
        { text = "🥗" }, { text = "🍿" }, { text = "🧈" }, { text = "🧂" },
        { text = "🥫" }, { text = "🍱" }, { text = "🍘" }, { text = "🍙" },
        { text = "🍚" }, { text = "🍛" }, { text = "🍜" }, { text = "🍝" },
        { text = "🍠" }, { text = "🍢" }, { text = "🍣" }, { text = "🍤" },
        { text = "🍥" }, { text = "🥮" }, { text = "🍡" }, { text = "🥟" },
        { text = "🥠" }, { text = "🥡" }, { text = "🍦" }, { text = "🍧" },
        { text = "🍨" }, { text = "🍩" }, { text = "🍪" }, { text = "🎂" },
        { text = "🍰" }, { text = "🧁" }, { text = "🥧" }, { text = "🍫" },
        { text = "🍬" }, { text = "🍭" }, { text = "🍮" }, { text = "🍯" },
        { text = "🍼" }, { text = "🥛" }, { text = "☕" }, { text = "🫖" },
        { text = "🍵" }, { text = "🍶" }, { text = "🍾" }, { text = "🍷" },
        { text = "🍸" }, { text = "🍹" }, { text = "🍺" }, { text = "🍻" },
        { text = "🥂" }, { text = "🥃" }, { text = "🫗" }, { text = "🥤" },
        { text = "🧋" }, { text = "🧃" }, { text = "🧉" }, { text = "🧊" },
        { text = "🥢" }, { text = "🍽️" }, { text = "🍴" }, { text = "🥄" },
        { text = "🔪" }, { text = "🫙" }, { text = "🏺" }
      } },
    { id = "emoji_travel", type = "SINGLE", name = "旅行",
      keys = {
        { text = "🌍" }, { text = "🌎" }, { text = "🌏" }, { text = "🌐" },
        { text = "🗺️" }, { text = "🗾" }, { text = "🧭" }, { text = "🏔️" },
        { text = "⛰️" }, { text = "🛘" }, { text = "🌋" }, { text = "🗻" },
        { text = "🏕️" }, { text = "🏖️" }, { text = "🏜️" }, { text = "🏝️" },
        { text = "🏞️" }, { text = "🏟️" }, { text = "🏛️" }, { text = "🏗️" },
        { text = "🧱" }, { text = "🪨" }, { text = "🪵" }, { text = "🛖" },
        { text = "🏘️" }, { text = "🏚️" }, { text = "🏠" }, { text = "🏡" },
        { text = "🏢" }, { text = "🏣" }, { text = "🏤" }, { text = "🏥" },
        { text = "🏦" }, { text = "🏨" }, { text = "🏩" }, { text = "🏪" },
        { text = "🏫" }, { text = "🏬" }, { text = "🏭" }, { text = "🏯" },
        { text = "🏰" }, { text = "💒" }, { text = "🗼" }, { text = "🗽" },
        { text = "⛪" }, { text = "🕌" }, { text = "🛕" }, { text = "🕍" },
        { text = "⛩️" }, { text = "🕋" }, { text = "⛲" }, { text = "⛺" },
        { text = "🌁" }, { text = "🌃" }, { text = "🏙️" }, { text = "🌄" },
        { text = "🌅" }, { text = "🌆" }, { text = "🌇" }, { text = "🌉" },
        { text = "♨️" }, { text = "🎠" }, { text = "🛝" }, { text = "🎡" },
        { text = "🎢" }, { text = "💈" }, { text = "🎪" }, { text = "🚂" },
        { text = "🚃" }, { text = "🚄" }, { text = "🚅" }, { text = "🚆" },
        { text = "🚇" }, { text = "🚈" }, { text = "🚉" }, { text = "🚊" },
        { text = "🚝" }, { text = "🚞" }, { text = "🚋" }, { text = "🚌" },
        { text = "🚍" }, { text = "🚎" }, { text = "🚐" }, { text = "🚑" },
        { text = "🚒" }, { text = "🚓" }, { text = "🚔" }, { text = "🚕" },
        { text = "🚖" }, { text = "🚗" }, { text = "🚘" }, { text = "🚙" },
        { text = "🛻" }, { text = "🚚" }, { text = "🚛" }, { text = "🚜" },
        { text = "🏎️" }, { text = "🏍️" }, { text = "🛵" }, { text = "🦽" },
        { text = "🦼" }, { text = "🛺" }, { text = "🚲" }, { text = "🛴" },
        { text = "🛹" }, { text = "🛼" }, { text = "🚏" }, { text = "🛣️" },
        { text = "🛤️" }, { text = "🛢️" }, { text = "⛽" }, { text = "🛞" },
        { text = "🚨" }, { text = "🚥" }, { text = "🚦" }, { text = "🛑" },
        { text = "🚧" }, { text = "⚓" }, { text = "🛟" }, { text = "⛵" },
        { text = "🛶" }, { text = "🚤" }, { text = "🛳️" }, { text = "⛴️" },
        { text = "🛥️" }, { text = "🚢" }, { text = "✈️" }, { text = "🛩️" },
        { text = "🛫" }, { text = "🛬" }, { text = "🪂" }, { text = "💺" },
        { text = "🚁" }, { text = "🚟" }, { text = "🚠" }, { text = "🚡" },
        { text = "🛰️" }, { text = "🚀" }, { text = "🛸" }, { text = "🛎️" },
        { text = "🧳" }, { text = "⌛" }, { text = "⏳" }, { text = "⌚" },
        { text = "⏰" }, { text = "⏱️" }, { text = "⏲️" }, { text = "🕰️" },
        { text = "🕛" }, { text = "🕧" }, { text = "🕐" }, { text = "🕜" },
        { text = "🕑" }, { text = "🕝" }, { text = "🕒" }, { text = "🕞" },
        { text = "🕓" }, { text = "🕟" }, { text = "🕔" }, { text = "🕠" },
        { text = "🕕" }, { text = "🕡" }, { text = "🕖" }, { text = "🕢" },
        { text = "🕗" }, { text = "🕣" }, { text = "🕘" }, { text = "🕤" },
        { text = "🕙" }, { text = "🕥" }, { text = "🕚" }, { text = "🕦" },
        { text = "🌑" }, { text = "🌒" }, { text = "🌓" }, { text = "🌔" },
        { text = "🌕" }, { text = "🌖" }, { text = "🌗" }, { text = "🌘" },
        { text = "🌙" }, { text = "🌚" }, { text = "🌛" }, { text = "🌜" },
        { text = "🌡️" }, { text = "☀️" }, { text = "🌝" }, { text = "🌞" },
        { text = "🪐" }, { text = "⭐" }, { text = "🌟" }, { text = "🌠" },
        { text = "🌌" }, { text = "☁️" }, { text = "⛅" }, { text = "⛈️" },
        { text = "🌤️" }, { text = "🌥️" }, { text = "🌦️" }, { text = "🌧️" },
        { text = "🌨️" }, { text = "🌩️" }, { text = "🌪️" }, { text = "🌫️" },
        { text = "🌬️" }, { text = "🌀" }, { text = "🌈" }, { text = "🌂" },
        { text = "☂️" }, { text = "☔" }, { text = "⛱️" }, { text = "⚡" },
        { text = "❄️" }, { text = "☃️" }, { text = "⛄" }, { text = "☄️" },
        { text = "🔥" }, { text = "💧" }, { text = "🌊" }
      } },
    { id = "emoji_activities", type = "SINGLE", name = "活动",
      keys = {
        { text = "🎃" }, { text = "🎄" }, { text = "🎆" }, { text = "🎇" },
        { text = "🧨" }, { text = "✨" }, { text = "🎈" }, { text = "🎉" },
        { text = "🎊" }, { text = "🎋" }, { text = "🎍" }, { text = "🎎" },
        { text = "🎏" }, { text = "🎐" }, { text = "🎑" }, { text = "🧧" },
        { text = "🎀" }, { text = "🎁" }, { text = "🎗️" }, { text = "🎟️" },
        { text = "🎫" }, { text = "🎖️" }, { text = "🏆" }, { text = "🏅" },
        { text = "🥇" }, { text = "🥈" }, { text = "🥉" }, { text = "⚽" },
        { text = "⚾" }, { text = "🥎" }, { text = "🏀" }, { text = "🏐" },
        { text = "🏈" }, { text = "🏉" }, { text = "🎾" }, { text = "🥏" },
        { text = "🎳" }, { text = "🏏" }, { text = "🏑" }, { text = "🏒" },
        { text = "🥍" }, { text = "🏓" }, { text = "🏸" }, { text = "🥊" },
        { text = "🥋" }, { text = "🥅" }, { text = "⛳" }, { text = "⛸️" },
        { text = "🎣" }, { text = "🤿" }, { text = "🎽" }, { text = "🎿" },
        { text = "🛷" }, { text = "🥌" }, { text = "🎯" }, { text = "🪀" },
        { text = "🪁" }, { text = "🔫" }, { text = "🎱" }, { text = "🔮" },
        { text = "🪄" }, { text = "🎮" }, { text = "🕹️" }, { text = "🎰" },
        { text = "🎲" }, { text = "🧩" }, { text = "🧸" }, { text = "🪅" },
        { text = "🪩" }, { text = "🪆" }, { text = "♠️" }, { text = "♥️" },
        { text = "♦️" }, { text = "♣️" }, { text = "♟️" }, { text = "🃏" },
        { text = "🀄" }, { text = "🎴" }, { text = "🎭" }, { text = "🖼️" },
        { text = "🎨" }, { text = "🧵" }, { text = "🪡" }, { text = "🧶" },
        { text = "🪢" }
      } },
    { id = "emoji_objects", type = "SINGLE", name = "物品",
      keys = {
        { text = "👓" }, { text = "🕶️" }, { text = "🥽" }, { text = "🥼" },
        { text = "🦺" }, { text = "👔" }, { text = "👕" }, { text = "👖" },
        { text = "🧣" }, { text = "🧤" }, { text = "🧥" }, { text = "🧦" },
        { text = "👗" }, { text = "👘" }, { text = "🥻" }, { text = "🩱" },
        { text = "🩲" }, { text = "🩳" }, { text = "👙" }, { text = "👚" },
        { text = "🪭" }, { text = "👛" }, { text = "👜" }, { text = "👝" },
        { text = "🛍️" }, { text = "🎒" }, { text = "🩴" }, { text = "👞" },
        { text = "👟" }, { text = "🥾" }, { text = "🥿" }, { text = "👠" },
        { text = "👡" }, { text = "🩰" }, { text = "👢" }, { text = "🪮" },
        { text = "👑" }, { text = "👒" }, { text = "🎩" }, { text = "🎓" },
        { text = "🧢" }, { text = "🪖" }, { text = "⛑️" }, { text = "📿" },
        { text = "💄" }, { text = "💍" }, { text = "💎" }, { text = "🔇" },
        { text = "🔈" }, { text = "🔉" }, { text = "🔊" }, { text = "📢" },
        { text = "📣" }, { text = "📯" }, { text = "🔔" }, { text = "🔕" },
        { text = "🎼" }, { text = "🎵" }, { text = "🎶" }, { text = "🎙️" },
        { text = "🎚️" }, { text = "🎛️" }, { text = "🎤" }, { text = "🎧" },
        { text = "📻" }, { text = "🎷" }, { text = "🎺" }, { text = "🪊" },
        { text = "🪗" }, { text = "🎸" }, { text = "🎹" }, { text = "🎻" },
        { text = "🪕" }, { text = "🥁" }, { text = "🪘" }, { text = "🪇" },
        { text = "🪈" }, { text = "🪉" }, { text = "📱" }, { text = "📲" },
        { text = "☎️" }, { text = "📞" }, { text = "📟" }, { text = "📠" },
        { text = "🔋" }, { text = "🪫" }, { text = "🔌" }, { text = "💻" },
        { text = "🖥️" }, { text = "🖨️" }, { text = "⌨️" }, { text = "🖱️" },
        { text = "🖲️" }, { text = "💽" }, { text = "💾" }, { text = "💿" },
        { text = "📀" }, { text = "🧮" }, { text = "🎥" }, { text = "🎞️" },
        { text = "📽️" }, { text = "🎬" }, { text = "📺" }, { text = "📷" },
        { text = "📸" }, { text = "📹" }, { text = "📼" }, { text = "🔍" },
        { text = "🔎" }, { text = "🕯️" }, { text = "💡" }, { text = "🔦" },
        { text = "🏮" }, { text = "🪔" }, { text = "📔" }, { text = "📕" },
        { text = "📖" }, { text = "📗" }, { text = "📘" }, { text = "📙" },
        { text = "📚" }, { text = "📓" }, { text = "📒" }, { text = "📃" },
        { text = "📜" }, { text = "📄" }, { text = "📰" }, { text = "🗞️" },
        { text = "📑" }, { text = "🔖" }, { text = "🏷️" }, { text = "🪙" },
        { text = "💰" }, { text = "🪎" }, { text = "💴" }, { text = "💵" },
        { text = "💶" }, { text = "💷" }, { text = "💸" }, { text = "💳" },
        { text = "🧾" }, { text = "💹" }, { text = "✉️" }, { text = "📧" },
        { text = "📨" }, { text = "📩" }, { text = "📤" }, { text = "📥" },
        { text = "📦" }, { text = "📫" }, { text = "📪" }, { text = "📬" },
        { text = "📭" }, { text = "📮" }, { text = "🗳️" }, { text = "✏️" },
        { text = "✒️" }, { text = "🖋️" }, { text = "🖊️" }, { text = "🖌️" },
        { text = "🖍️" }, { text = "📝" }, { text = "💼" }, { text = "📁" },
        { text = "📂" }, { text = "🗂️" }, { text = "📅" }, { text = "📆" },
        { text = "🗒️" }, { text = "🗓️" }, { text = "📇" }, { text = "📈" },
        { text = "📉" }, { text = "📊" }, { text = "📋" }, { text = "📌" },
        { text = "📍" }, { text = "📎" }, { text = "🖇️" }, { text = "📏" },
        { text = "📐" }, { text = "✂️" }, { text = "🗃️" }, { text = "🗄️" },
        { text = "🗑️" }, { text = "🔒" }, { text = "🔓" }, { text = "🔏" },
        { text = "🔐" }, { text = "🔑" }, { text = "🗝️" }, { text = "🔨" },
        { text = "🪓" }, { text = "⛏️" }, { text = "⚒️" }, { text = "🛠️" },
        { text = "🗡️" }, { text = "⚔️" }, { text = "💣" }, { text = "🪃" },
        { text = "🏹" }, { text = "🛡️" }, { text = "🪚" }, { text = "🔧" },
        { text = "🪛" }, { text = "🔩" }, { text = "⚙️" }, { text = "🗜️" },
        { text = "⚖️" }, { text = "🦯" }, { text = "🔗" }, { text = "⛓️‍💥" },
        { text = "⛓️" }, { text = "🪝" }, { text = "🧰" }, { text = "🧲" },
        { text = "🪜" }, { text = "🪏" }, { text = "⚗️" }, { text = "🧪" },
        { text = "🧫" }, { text = "🧬" }, { text = "🔬" }, { text = "🔭" },
        { text = "📡" }, { text = "💉" }, { text = "🩸" }, { text = "💊" },
        { text = "🩹" }, { text = "🩼" }, { text = "🩺" }, { text = "🩻" },
        { text = "🚪" }, { text = "🛗" }, { text = "🪞" }, { text = "🪟" },
        { text = "🛏️" }, { text = "🛋️" }, { text = "🪑" }, { text = "🚽" },
        { text = "🪠" }, { text = "🚿" }, { text = "🛁" }, { text = "🪤" },
        { text = "🪒" }, { text = "🧴" }, { text = "🧷" }, { text = "🧹" },
        { text = "🧺" }, { text = "🧻" }, { text = "🪣" }, { text = "🧼" },
        { text = "🫧" }, { text = "🪥" }, { text = "🧽" }, { text = "🧯" },
        { text = "🛒" }, { text = "🚬" }, { text = "⚰️" }, { text = "🪦" },
        { text = "⚱️" }, { text = "🧿" }, { text = "🪬" }, { text = "🗿" },
        { text = "🪧" }, { text = "🪪" }
      } },
    { id = "emoji_symbols", type = "SINGLE", name = "符号",
      keys = {
        { text = "🏧" }, { text = "🚮" }, { text = "🚰" }, { text = "♿" },
        { text = "🚹" }, { text = "🚺" }, { text = "🚻" }, { text = "🚼" },
        { text = "🚾" }, { text = "🛂" }, { text = "🛃" }, { text = "🛄" },
        { text = "🛅" }, { text = "⚠️" }, { text = "🚸" }, { text = "⛔" },
        { text = "🚫" }, { text = "🚳" }, { text = "🚭" }, { text = "🚯" },
        { text = "🚱" }, { text = "🚷" }, { text = "📵" }, { text = "🔞" },
        { text = "☢️" }, { text = "☣️" }, { text = "⬆️" }, { text = "↗️" },
        { text = "➡️" }, { text = "↘️" }, { text = "⬇️" }, { text = "↙️" },
        { text = "⬅️" }, { text = "↖️" }, { text = "↕️" }, { text = "↔️" },
        { text = "↩️" }, { text = "↪️" }, { text = "⤴️" }, { text = "⤵️" },
        { text = "🔃" }, { text = "🔄" }, { text = "🔙" }, { text = "🔚" },
        { text = "🔛" }, { text = "🔜" }, { text = "🔝" }, { text = "🛐" },
        { text = "⚛️" }, { text = "🕉️" }, { text = "✡️" }, { text = "☸️" },
        { text = "☯️" }, { text = "✝️" }, { text = "☦️" }, { text = "☪️" },
        { text = "☮️" }, { text = "🕎" }, { text = "🔯" }, { text = "🪯" },
        { text = "♈" }, { text = "♉" }, { text = "♊" }, { text = "♋" },
        { text = "♌" }, { text = "♍" }, { text = "♎" }, { text = "♏" },
        { text = "♐" }, { text = "♑" }, { text = "♒" }, { text = "♓" },
        { text = "⛎" }, { text = "🔀" }, { text = "🔁" }, { text = "🔂" },
        { text = "▶️" }, { text = "⏩" }, { text = "⏭️" }, { text = "⏯️" },
        { text = "◀️" }, { text = "⏪" }, { text = "⏮️" }, { text = "🔼" },
        { text = "⏫" }, { text = "🔽" }, { text = "⏬" }, { text = "⏸️" },
        { text = "⏹️" }, { text = "⏺️" }, { text = "⏏️" }, { text = "🎦" },
        { text = "🔅" }, { text = "🔆" }, { text = "📶" }, { text = "🛜" },
        { text = "📳" }, { text = "📴" }, { text = "♀️" }, { text = "♂️" },
        { text = "⚧️" }, { text = "✖️" }, { text = "➕" }, { text = "➖" },
        { text = "➗" }, { text = "🟰" }, { text = "♾️" }, { text = "‼️" },
        { text = "⁉️" }, { text = "❓" }, { text = "❔" }, { text = "❕" },
        { text = "❗" }, { text = "〰️" }, { text = "💱" }, { text = "💲" },
        { text = "⚕️" }, { text = "♻️" }, { text = "⚜️" }, { text = "🔱" },
        { text = "📛" }, { text = "🔰" }, { text = "⭕" }, { text = "✅" },
        { text = "☑️" }, { text = "✔️" }, { text = "❌" }, { text = "❎" },
        { text = "➰" }, { text = "➿" }, { text = "〽️" }, { text = "✳️" },
        { text = "✴️" }, { text = "❇️" }, { text = "©️" }, { text = "®️" },
        { text = "™️" }, { text = "🫟" }, { text = "#️⃣" }, { text = "*️⃣" },
        { text = "0️⃣" }, { text = "1️⃣" }, { text = "2️⃣" }, { text = "3️⃣" },
        { text = "4️⃣" }, { text = "5️⃣" }, { text = "6️⃣" }, { text = "7️⃣" },
        { text = "8️⃣" }, { text = "9️⃣" }, { text = "🔟" }, { text = "🔠" },
        { text = "🔡" }, { text = "🔢" }, { text = "🔣" }, { text = "🔤" },
        { text = "🅰️" }, { text = "🆎" }, { text = "🅱️" }, { text = "🆑" },
        { text = "🆒" }, { text = "🆓" }, { text = "ℹ️" }, { text = "🆔" },
        { text = "Ⓜ️" }, { text = "🆕" }, { text = "🆖" }, { text = "🅾️" },
        { text = "🆗" }, { text = "🅿️" }, { text = "🆘" }, { text = "🆙" },
        { text = "🆚" }, { text = "🈁" }, { text = "🈂️" }, { text = "🈷️" },
        { text = "🈶" }, { text = "🈯" }, { text = "🉐" }, { text = "🈹" },
        { text = "🈚" }, { text = "🈲" }, { text = "🉑" }, { text = "🈸" },
        { text = "🈴" }, { text = "🈳" }, { text = "㊗️" }, { text = "㊙️" },
        { text = "🈺" }, { text = "🈵" }, { text = "🔴" }, { text = "🟠" },
        { text = "🟡" }, { text = "🟢" }, { text = "🔵" }, { text = "🟣" },
        { text = "🟤" }, { text = "⚫" }, { text = "⚪" }, { text = "🟥" },
        { text = "🟧" }, { text = "🟨" }, { text = "🟩" }, { text = "🟦" },
        { text = "🟪" }, { text = "🟫" }, { text = "⬛" }, { text = "⬜" },
        { text = "◼️" }, { text = "◻️" }, { text = "◾" }, { text = "◽" },
        { text = "▪️" }, { text = "▫️" }, { text = "🔶" }, { text = "🔷" },
        { text = "🔸" }, { text = "🔹" }, { text = "🔺" }, { text = "🔻" },
        { text = "💠" }, { text = "🔘" }, { text = "🔳" }, { text = "🔲" }
      } },
    { id = "emoji_flags", type = "SINGLE", name = "旗帜",
      keys = {
        { text = "🏁" }, { text = "🚩" }, { text = "🎌" }, { text = "🏴" },
        { text = "🏳️" }, { text = "🏳️‍🌈" }, { text = "🏳️‍⚧️" }, { text = "🏴‍☠️" },
        { text = "🇦🇨" }, { text = "🇦🇩" }, { text = "🇦🇪" }, { text = "🇦🇫" },
        { text = "🇦🇬" }, { text = "🇦🇮" }, { text = "🇦🇱" }, { text = "🇦🇲" },
        { text = "🇦🇴" }, { text = "🇦🇶" }, { text = "🇦🇷" }, { text = "🇦🇸" },
        { text = "🇦🇹" }, { text = "🇦🇺" }, { text = "🇦🇼" }, { text = "🇦🇽" },
        { text = "🇦🇿" }, { text = "🇧🇦" }, { text = "🇧🇧" }, { text = "🇧🇩" },
        { text = "🇧🇪" }, { text = "🇧🇫" }, { text = "🇧🇬" }, { text = "🇧🇭" },
        { text = "🇧🇮" }, { text = "🇧🇯" }, { text = "🇧🇱" }, { text = "🇧🇲" },
        { text = "🇧🇳" }, { text = "🇧🇴" }, { text = "🇧🇶" }, { text = "🇧🇷" },
        { text = "🇧🇸" }, { text = "🇧🇹" }, { text = "🇧🇻" }, { text = "🇧🇼" },
        { text = "🇧🇾" }, { text = "🇧🇿" }, { text = "🇨🇦" }, { text = "🇨🇨" },
        { text = "🇨🇩" }, { text = "🇨🇫" }, { text = "🇨🇬" }, { text = "🇨🇭" },
        { text = "🇨🇮" }, { text = "🇨🇰" }, { text = "🇨🇱" }, { text = "🇨🇲" },
        { text = "🇨🇳" }, { text = "🇨🇴" }, { text = "🇨🇵" }, { text = "🇨🇶" },
        { text = "🇨🇷" }, { text = "🇨🇺" }, { text = "🇨🇻" }, { text = "🇨🇼" },
        { text = "🇨🇽" }, { text = "🇨🇾" }, { text = "🇨🇿" }, { text = "🇩🇪" },
        { text = "🇩🇬" }, { text = "🇩🇯" }, { text = "🇩🇰" }, { text = "🇩🇲" },
        { text = "🇩🇴" }, { text = "🇩🇿" }, { text = "🇪🇦" }, { text = "🇪🇨" },
        { text = "🇪🇪" }, { text = "🇪🇬" }, { text = "🇪🇭" }, { text = "🇪🇷" },
        { text = "🇪🇸" }, { text = "🇪🇹" }, { text = "🇪🇺" }, { text = "🇫🇮" },
        { text = "🇫🇯" }, { text = "🇫🇰" }, { text = "🇫🇲" }, { text = "🇫🇴" },
        { text = "🇫🇷" }, { text = "🇬🇦" }, { text = "🇬🇧" }, { text = "🇬🇩" },
        { text = "🇬🇪" }, { text = "🇬🇫" }, { text = "🇬🇬" }, { text = "🇬🇭" },
        { text = "🇬🇮" }, { text = "🇬🇱" }, { text = "🇬🇲" }, { text = "🇬🇳" },
        { text = "🇬🇵" }, { text = "🇬🇶" }, { text = "🇬🇷" }, { text = "🇬🇸" },
        { text = "🇬🇹" }, { text = "🇬🇺" }, { text = "🇬🇼" }, { text = "🇬🇾" },
        { text = "🇭🇰" }, { text = "🇭🇲" }, { text = "🇭🇳" }, { text = "🇭🇷" },
        { text = "🇭🇹" }, { text = "🇭🇺" }, { text = "🇮🇨" }, { text = "🇮🇩" },
        { text = "🇮🇪" }, { text = "🇮🇱" }, { text = "🇮🇲" }, { text = "🇮🇳" },
        { text = "🇮🇴" }, { text = "🇮🇶" }, { text = "🇮🇷" }, { text = "🇮🇸" },
        { text = "🇮🇹" }, { text = "🇯🇪" }, { text = "🇯🇲" }, { text = "🇯🇴" },
        { text = "🇯🇵" }, { text = "🇰🇪" }, { text = "🇰🇬" }, { text = "🇰🇭" },
        { text = "🇰🇮" }, { text = "🇰🇲" }, { text = "🇰🇳" }, { text = "🇰🇵" },
        { text = "🇰🇷" }, { text = "🇰🇼" }, { text = "🇰🇾" }, { text = "🇰🇿" },
        { text = "🇱🇦" }, { text = "🇱🇧" }, { text = "🇱🇨" }, { text = "🇱🇮" },
        { text = "🇱🇰" }, { text = "🇱🇷" }, { text = "🇱🇸" }, { text = "🇱🇹" },
        { text = "🇱🇺" }, { text = "🇱🇻" }, { text = "🇱🇾" }, { text = "🇲🇦" },
        { text = "🇲🇨" }, { text = "🇲🇩" }, { text = "🇲🇪" }, { text = "🇲🇫" },
        { text = "🇲🇬" }, { text = "🇲🇭" }, { text = "🇲🇰" }, { text = "🇲🇱" },
        { text = "🇲🇲" }, { text = "🇲🇳" }, { text = "🇲🇴" }, { text = "🇲🇵" },
        { text = "🇲🇶" }, { text = "🇲🇷" }, { text = "🇲🇸" }, { text = "🇲🇹" },
        { text = "🇲🇺" }, { text = "🇲🇻" }, { text = "🇲🇼" }, { text = "🇲🇽" },
        { text = "🇲🇾" }, { text = "🇲🇿" }, { text = "🇳🇦" }, { text = "🇳🇨" },
        { text = "🇳🇪" }, { text = "🇳🇫" }, { text = "🇳🇬" }, { text = "🇳🇮" },
        { text = "🇳🇱" }, { text = "🇳🇴" }, { text = "🇳🇵" }, { text = "🇳🇷" },
        { text = "🇳🇺" }, { text = "🇳🇿" }, { text = "🇴🇲" }, { text = "🇵🇦" },
        { text = "🇵🇪" }, { text = "🇵🇫" }, { text = "🇵🇬" }, { text = "🇵🇭" },
        { text = "🇵🇰" }, { text = "🇵🇱" }, { text = "🇵🇲" }, { text = "🇵🇳" },
        { text = "🇵🇷" }, { text = "🇵🇸" }, { text = "🇵🇹" }, { text = "🇵🇼" },
        { text = "🇵🇾" }, { text = "🇶🇦" }, { text = "🇷🇪" }, { text = "🇷🇴" },
        { text = "🇷🇸" }, { text = "🇷🇺" }, { text = "🇷🇼" }, { text = "🇸🇦" },
        { text = "🇸🇧" }, { text = "🇸🇨" }, { text = "🇸🇩" }, { text = "🇸🇪" },
        { text = "🇸🇬" }, { text = "🇸🇭" }, { text = "🇸🇮" }, { text = "🇸🇯" },
        { text = "🇸🇰" }, { text = "🇸🇱" }, { text = "🇸🇲" }, { text = "🇸🇳" },
        { text = "🇸🇴" }, { text = "🇸🇷" }, { text = "🇸🇸" }, { text = "🇸🇹" },
        { text = "🇸🇻" }, { text = "🇸🇽" }, { text = "🇸🇾" }, { text = "🇸🇿" },
        { text = "🇹🇦" }, { text = "🇹🇨" }, { text = "🇹🇩" }, { text = "🇹🇫" },
        { text = "🇹🇬" }, { text = "🇹🇭" }, { text = "🇹🇯" }, { text = "🇹🇰" },
        { text = "🇹🇱" }, { text = "🇹🇲" }, { text = "🇹🇳" }, { text = "🇹🇴" },
        { text = "🇹🇷" }, { text = "🇹🇹" }, { text = "🇹🇻" }, { text = "🇹🇼" },
        { text = "🇹🇿" }, { text = "🇺🇦" }, { text = "🇺🇬" }, { text = "🇺🇲" },
        { text = "🇺🇳" }, { text = "🇺🇸" }, { text = "🇺🇾" }, { text = "🇺🇿" },
        { text = "🇻🇦" }, { text = "🇻🇨" }, { text = "🇻🇪" }, { text = "🇻🇬" },
        { text = "🇻🇮" }, { text = "🇻🇳" }, { text = "🇻🇺" }, { text = "🇼🇫" },
        { text = "🇼🇸" }, { text = "🇽🇰" }, { text = "🇾🇪" }, { text = "🇾🇹" },
        { text = "🇿🇦" }, { text = "🇿🇲" }, { text = "🇿🇼" }, { text = "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
        { text = "🏴󠁧󠁢󠁳󠁣󠁴󠁿" }, { text = "🏴󠁧󠁢󠁷󠁬󠁳󠁿" }
      } },
    { id = "hiragana", type = "SINGLE", name = "平假",
      keys = {
        -- あ行 / か行
        { text = "あ" }, { text = "い" }, { text = "う" }, { text = "え" },
        { text = "お" }, { text = "か" }, { text = "き" }, { text = "く" },
        -- か行(续) / さ行
        { text = "け" }, { text = "こ" }, { text = "さ" }, { text = "し" },
        { text = "す" }, { text = "せ" }, { text = "そ" }, { text = "た" },
        -- た行 / な行
        { text = "ち" }, { text = "つ" }, { text = "て" }, { text = "と" },
        { text = "な" }, { text = "に" }, { text = "ぬ" }, { text = "ね" },
        -- な行(续) / は行
        { text = "の" }, { text = "は" }, { text = "ひ" }, { text = "ふ" },
        { text = "へ" }, { text = "ほ" }, { text = "ま" }, { text = "み" },
        -- ま行(续) / や行 / ら行
        { text = "む" }, { text = "め" }, { text = "も" }, { text = "や" },
        { text = "ゆ" }, { text = "よ" }, { text = "ら" }, { text = "り" },
        -- ら行(续) / わ行
        { text = "る" }, { text = "れ" }, { text = "ろ" }, { text = "わ" },
        { text = "を" }, { text = "ん" },
        -- 濁音 が行 / ざ行
        { text = "が" }, { text = "ぎ" }, { text = "ぐ" }, { text = "げ" },
        { text = "ご" }, { text = "ざ" }, { text = "じ" }, { text = "ず" },
        -- 濁音(续) / だ行 / ば行
        { text = "ぜ" }, { text = "ぞ" }, { text = "だ" }, { text = "ぢ" },
        { text = "づ" }, { text = "で" }, { text = "ど" }, { text = "ば" },
        -- 濁音(续) / ぱ行
        { text = "び" }, { text = "ぶ" }, { text = "べ" }, { text = "ぼ" },
        { text = "ぱ" }, { text = "ぴ" }, { text = "ぷ" }, { text = "ぺ" },
        -- ぱ行(续) / 小書き
        { text = "ぽ" }, { text = "ぁ" }, { text = "ぃ" }, { text = "ぅ" },
        { text = "ぇ" }, { text = "ぉ" }, { text = "ゃ" }, { text = "ゅ" },
        -- 小書き(续)
        { text = "ょ" }, { text = "っ" }
      } },
    { id = "katakana", type = "SINGLE", name = "片假",
      keys = {
        -- ア行 / カ行
        { text = "ア" }, { text = "イ" }, { text = "ウ" }, { text = "エ" },
        { text = "オ" }, { text = "カ" }, { text = "キ" }, { text = "ク" },
        -- カ行(续) / サ行
        { text = "ケ" }, { text = "コ" }, { text = "サ" }, { text = "シ" },
        { text = "ス" }, { text = "セ" }, { text = "ソ" }, { text = "タ" },
        -- タ行 / ナ行
        { text = "チ" }, { text = "ツ" }, { text = "テ" }, { text = "ト" },
        { text = "ナ" }, { text = "ニ" }, { text = "ヌ" }, { text = "ネ" },
        -- ナ行(续) / ハ行
        { text = "ノ" }, { text = "ハ" }, { text = "ヒ" }, { text = "フ" },
        { text = "ヘ" }, { text = "ホ" }, { text = "マ" }, { text = "ミ" },
        -- マ行(续) / ヤ行 / ラ行
        { text = "ム" }, { text = "メ" }, { text = "モ" }, { text = "ヤ" },
        { text = "ユ" }, { text = "ヨ" }, { text = "ラ" }, { text = "リ" },
        -- ラ行(续) / ワ行
        { text = "ル" }, { text = "レ" }, { text = "ロ" }, { text = "ワ" },
        { text = "ヲ" }, { text = "ン" }, { text = "ー" },
        -- 濁音 ガ行 / ザ行
        { text = "ガ" }, { text = "ギ" }, { text = "グ" }, { text = "ゲ" },
        { text = "ゴ" }, { text = "ザ" }, { text = "ジ" }, { text = "ズ" },
        -- 濁音(续) / ダ行 / バ行
        { text = "ゼ" }, { text = "ゾ" }, { text = "ダ" }, { text = "ヂ" },
        { text = "ヅ" }, { text = "デ" }, { text = "ド" }, { text = "バ" },
        -- 濁音(续) / パ行
        { text = "ビ" }, { text = "ブ" }, { text = "ベ" }, { text = "ボ" },
        { text = "パ" }, { text = "ピ" }, { text = "プ" }, { text = "ペ" },
        -- パ行(续) / 小書き
        { text = "ポ" }, { text = "ァ" }, { text = "ィ" }, { text = "ゥ" },
        { text = "ェ" }, { text = "ォ" }, { text = "ャ" }, { text = "ュ" },
        -- 小書き(续)
        { text = "ョ" }, { text = "ッ" }
      } },
    { id = "greek", type = "SINGLE", name = "希腊",
      keys = {
        -- 标准小写 α-ω (25, 含 final sigma)
        { text = "α" }, { text = "β" }, { text = "γ" }, { text = "δ" },
        { text = "ε" }, { text = "ζ" }, { text = "η" }, { text = "θ" },
        { text = "ι" }, { text = "κ" }, { text = "λ" }, { text = "μ" },
        { text = "ν" }, { text = "ξ" }, { text = "ο" }, { text = "π" },
        { text = "ρ" }, { text = "ς" }, { text = "σ" }, { text = "τ" },
        { text = "υ" }, { text = "φ" }, { text = "χ" }, { text = "ψ" },
        { text = "ω" },
        -- 标准大写 Α-Ω (24)
        { text = "Α" }, { text = "Β" }, { text = "Γ" }, { text = "Δ" },
        { text = "Ε" }, { text = "Ζ" }, { text = "Η" }, { text = "Θ" },
        { text = "Ι" }, { text = "Κ" }, { text = "Λ" }, { text = "Μ" },
        { text = "Ν" }, { text = "Ξ" }, { text = "Ο" }, { text = "Π" },
        { text = "Ρ" }, { text = "Σ" }, { text = "Τ" }, { text = "Υ" },
        { text = "Φ" }, { text = "Χ" }, { text = "Ψ" }, { text = "Ω" },
        -- 古体字母 (7)
        { text = "Ͱ" }, { text = "ͱ" }, { text = "Ͳ" }, { text = "ͳ" },
        { text = "Ͷ" }, { text = "ͷ" }, { text = "Ϳ" }, { text = "ͺ" },
        -- 变体符号 (7)
        { text = "ͻ" }, { text = "ͼ" }, { text = "ͽ" }, { text = "Ͻ" },
        { text = "Ͼ" }, { text = "Ͽ" }, { text = "ϳ" },
        -- 数字/标点 (4)
        { text = "ʹ" }, { text = "͵" }, { text = ";" }, { text = "·" },
        -- 声调/分音符号 (3)
        { text = "΄" }, { text = "΅" },
        -- 带声调大写 (7)
        { text = "Ά" }, { text = "Έ" }, { text = "Ή" }, { text = "Ί" },
        { text = "Ό" }, { text = "Ύ" }, { text = "Ώ" },
        -- 带分音大写 (2)
        { text = "Ϊ" }, { text = "Ϋ" },
        -- 带声调/分音小写 (8)
        { text = "ά" }, { text = "έ" }, { text = "ή" }, { text = "ί" },
        { text = "ό" }, { text = "ύ" }, { text = "ώ" },
        { text = "ΐ" }, { text = "ΰ" }, { text = "ϊ" }, { text = "ϋ" },
        -- Kai 符号
        { text = "Ϗ" }, { text = "ϗ" },
        -- 变体字母符号 (11)
        { text = "ϐ" }, { text = "ϑ" }, { text = "ϒ" }, { text = "ϓ" },
        { text = "ϔ" }, { text = "ϕ" }, { text = "ϖ" }, { text = "ϰ" },
        { text = "ϱ" }, { text = "ϴ" }, { text = "ϵ" },
        -- 古代/特殊字母 (16)
        { text = "Ϙ" }, { text = "ϙ" }, { text = "Ϛ" }, { text = "ϛ" },
        { text = "Ϝ" }, { text = "ϝ" }, { text = "Ϟ" }, { text = "ϟ" },
        { text = "Ϡ" }, { text = "ϡ" }, { text = "Ϻ" }, { text = "ϻ" },
        { text = "Ϲ" }, { text = "ϲ" }, { text = "϶" }, { text = "ϼ" },
        -- 其他变体 (2)
        { text = "Ϸ" }, { text = "ϸ" },
        -- 科普特字母 (16)
        { text = "Ϣ" }, { text = "ϣ" }, { text = "Ϥ" }, { text = "ϥ" },
        { text = "Ϧ" }, { text = "ϧ" }, { text = "Ϩ" }, { text = "ϩ" },
        { text = "Ϫ" }, { text = "ϫ" }, { text = "Ϭ" }, { text = "ϭ" },
        { text = "Ϯ" }, { text = "ϯ" }
      } },
    { id = "hangul", type = "SINGLE", name = "韩文",
      keys = {
        -- 基本辅音 (14)
        { text = "ㄱ" }, { text = "ㄴ" }, { text = "ㄷ" }, { text = "ㄹ" },
        { text = "ㅁ" }, { text = "ㅂ" }, { text = "ㅅ" }, { text = "ㅇ" },
        { text = "ㅈ" }, { text = "ㅊ" }, { text = "ㅋ" }, { text = "ㅌ" },
        { text = "ㅍ" }, { text = "ㅎ" },
        -- 双辅音 (5)
        { text = "ㄲ" }, { text = "ㄸ" }, { text = "ㅃ" }, { text = "ㅆ" },
        { text = "ㅉ" },
        -- 辅音簇 (11)
        { text = "ㄳ" }, { text = "ㄵ" }, { text = "ㄶ" }, { text = "ㄺ" },
        { text = "ㄻ" }, { text = "ㄼ" }, { text = "ㄽ" }, { text = "ㄾ" },
        { text = "ㄿ" }, { text = "ㅀ" }, { text = "ㅄ" },
        -- 基本元音 (10)
        { text = "ㅏ" }, { text = "ㅑ" }, { text = "ㅓ" }, { text = "ㅕ" },
        { text = "ㅗ" }, { text = "ㅛ" }, { text = "ㅜ" }, { text = "ㅠ" },
        { text = "ㅡ" }, { text = "ㅣ" },
        -- 复合元音 (11)
        { text = "ㅐ" }, { text = "ㅒ" }, { text = "ㅔ" }, { text = "ㅖ" },
        { text = "ㅘ" }, { text = "ㅙ" }, { text = "ㅚ" }, { text = "ㅝ" },
        { text = "ㅞ" }, { text = "ㅟ" }, { text = "ㅢ" }
      } },
    { id = "hangul_old", type = "SINGLE", name = "谚文",
      keys = {
        -- 古谚文辅音扩展 (42)
        { text = "ㅥ" }, { text = "ㅦ" }, { text = "ㅧ" }, { text = "ㅨ" },
        { text = "ㅩ" }, { text = "ㅪ" }, { text = "ㅫ" }, { text = "ㅬ" },
        { text = "ㅭ" }, { text = "ㅮ" }, { text = "ㅯ" }, { text = "ㅰ" },
        { text = "ㅱ" }, { text = "ㅲ" }, { text = "ㅳ" }, { text = "ㅴ" },
        { text = "ㅵ" }, { text = "ㅶ" }, { text = "ㅷ" }, { text = "ㅸ" },
        { text = "ㅹ" }, { text = "ㅺ" }, { text = "ㅻ" }, { text = "ㅼ" },
        { text = "ㅽ" }, { text = "ㅾ" }, { text = "ㅿ" }, { text = "ㆀ" },
        { text = "ㆁ" }, { text = "ㆂ" }, { text = "ㆃ" }, { text = "ㆄ" },
        { text = "ㆅ" }, { text = "ㆆ" }, { text = "ㆇ" }, { text = "ㆈ" },
        { text = "ㆉ" }, { text = "ㆊ" }, { text = "ㆋ" }, { text = "ㆌ" },
        { text = "ㆍ" }, { text = "ㆎ" }
      } }
  }
}

return liquid
